<?xml version="1.0" encoding="utf-8"?><Database Name="HotelDB" Class="RoomDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0MT6QTG;Initial Catalog=HotelDB;Integrated Security=True;Pooling=False;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HotelDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roomNun" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kindOfRoom" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="isAvelible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>